### ISSUE TITLE
Problem in navigation bar

### ISSUE THREAD

**Issue by Abhi7790154** [roshishshigu/E-challan-management-system#1]
Place the last 3 navigation links into dropdown.

![issue 3](https://user-images.githubusercontent.com/81900923/114974068-6c5eaf80-9ea1-11eb-8acc-fe4268cc6c61.png)

**Comment by rakshya-1** [comment]
Navigational Issue solved

![issue 3 result](https://user-images.githubusercontent.com/81901529/114974743-b09e7f80-9ea2-11eb-9978-dd5a2e64fc0d.png)
