### ISSUE TITLE
Problem with arrangement in Navigational links 

### ISSUE THREAD

**Issue by bibekjungthapa** [roshishshigu/E-challan-management-system#2]
Place the last 3 navigational link in a dropdown

![rakshya_issue](https://user-images.githubusercontent.com/77617939/114976336-87332300-9ea5-11eb-896c-c0c98e1713e6.png)

**Comment by rakshya-1** [comment]
Dropdown added in the navigation bar.

![issue 3 result (1)](https://user-images.githubusercontent.com/81901529/114976491-c8c3ce00-9ea5-11eb-983f-63abeef07ced.png)
