### ISSUE TITLE
Problem with Signin Page

### ISSUE THREAD

**Issue by bibekjungthapa** [roshishshigu/E-challan-management-system#3]
Add the place holder in the input fields
![issue1](https://user-images.githubusercontent.com/77617939/114976787-4ab3f700-9ea6-11eb-8e8e-ac6a5fa8667e.PNG)

**Comment by Abhi7790154** [comment]
Added the placeholder 

![issue solved](https://user-images.githubusercontent.com/81900923/114977649-bcd90b80-9ea7-11eb-9cb2-1dca04ff878d.PNG)
