### ISSUE TITLE
Issue regarding active user 

### ISSUE THREAD

**Issue by bibekjungthapa** [roshishshigu/E-challan-management-system#4]
Display the active user on the navigation bar and automatically add the user in the 'created by' field.

![image](https://user-images.githubusercontent.com/77617939/114977968-4b4d8d00-9ea8-11eb-8780-7e924d0e54cb.png)

**Comment by Abhiyan77** [comment]
Issue solved !! Added the active user on the top right side of the page and automatically placed the user name in 'Created By' field

![issue 2 result](https://user-images.githubusercontent.com/81901432/114978965-c794a000-9ea9-11eb-8b33-c179530f98b8.png)
