### ISSUE TITLE
Admin panel navigational element not visible if the admin is logged in

### ISSUE THREAD

**Issue by bibekjungthapa** [roshishshigu/E-challan-management-system#5]
![abhiyan_issue](https://user-images.githubusercontent.com/77617939/117862243-29caa000-b2b2-11eb-8749-61a8d84571bb.png)

**Comment by Abhiyan77** [comment]
![abhiyan_solution](https://user-images.githubusercontent.com/81901432/117862855-d9077700-b2b2-11eb-8a5c-cdbf2629f1a3.png)


I've made the Admin panel link visible in the navigation menu if the admin is logged is and is not visible if the other users are logged in.
