### ISSUE TITLE
There is no any numbering to show how my challan have been created by user, please fix this issue by showing the number count

### ISSUE THREAD

**Issue by bibekjungthapa** [roshishshigu/E-challan-management-system#6]
![abhishek_issue](https://user-images.githubusercontent.com/77617939/117863645-b9bd1980-b2b3-11eb-8de3-c73994cf2ead.png)

**Comment by Abhi7790154** [comment]
![abhishek_solution](https://user-images.githubusercontent.com/81900923/117863989-0e609480-b2b4-11eb-8195-0a7a9d929b76.png)
I have added the  challan count on top left corner, and resolve the issue.
