### ISSUE TITLE
Form Borders are not visible and add the background image 

### ISSUE THREAD

**Issue by bibekjungthapa** [roshishshigu/E-challan-management-system#7]
![rakshya_issue](https://user-images.githubusercontent.com/77617939/117864260-4ff13f80-b2b4-11eb-9f12-8116bc2e66a7.png)

**Comment by rakshya-1** [comment]
![rakshya_solution](https://user-images.githubusercontent.com/81901529/118007170-9f467700-b36b-11eb-853a-06414ae17a3c.png)
Form Borders has been visible . Backgroud image has been added.
